import type { Match } from "@/types/match"

export const mockMatches: Match[] = [
  {
    id: "m1",
    vacancy: {
      id: "v1",
      companyName: "Vacancy Title",
      title: "Vacancy Title",
      level: "Junior",
      salaryEurBruto: 1600,
      location: "Riga",
      workFormat: "Hybrid",
      languages: ["Latvian", "English"],
      matchPercent: 85,
      description: "Interesting work in a dynamic team with development opportunities.",
      requirements: [
        "Good communication skills",
        "Ability to work in a team",
        "Motivation to learn",
      ],
    },
    status: "potential",
    interviewDate: "2026-05-09",
    interviewTime: "13:30-13:45",
    matchedAt: Date.now() - 86400000,
    companyRegistrationNumber: "26777365",
  },
  {
    id: "m2",
    vacancy: {
      id: "v2",
      companyName: "Vacancy Title",
      title: "Vacancy Title",
      level: "Mid",
      salaryEurBruto: 2200,
      location: "Riga",
      workFormat: "On-site",
      languages: ["Latvian"],
      matchPercent: 78,
      description: "Stable company with long-term experience in the market.",
      requirements: [
        "Experience in similar position",
        "Responsibility and accuracy",
        "Time management skills",
      ],
    },
    status: "potential",
    interviewDate: "2026-05-09",
    interviewTime: "13:30-13:45",
    matchedAt: Date.now() - 172800000,
    companyRegistrationNumber: "26777365",
  },
  {
    id: "m3",
    vacancy: {
      id: "v3",
      companyName: "Tech Solutions",
      title: "Junior Developer",
      level: "Junior",
      salaryEurBruto: 1800,
      location: "Riga",
      workFormat: "Remote",
      languages: ["English"],
      matchPercent: 92,
      description: "Modern tech company looking for talented juniors.",
      requirements: [
        "Basic programming knowledge",
        "Willingness to learn",
        "Good English",
      ],
    },
    status: "agreed",
    interviewDate: "2026-05-12",
    interviewTime: "14:00-14:30",
    matchedAt: Date.now() - 259200000,
    companyRegistrationNumber: "40003987654",
  },
  {
    id: "m4",
    vacancy: {
      id: "v4",
      companyName: "Creative Agency",
      title: "Content Creator",
      level: "Junior",
      salaryEurBruto: 1500,
      location: "Riga",
      workFormat: "Hybrid",
      languages: ["Latvian", "English"],
      matchPercent: 72,
      description: "Join our creative team and make impact.",
      requirements: [
        "Creative thinking",
        "Good communication",
        "Social media knowledge",
      ],
    },
    status: "thinking",
    matchedAt: Date.now() - 345600000,
    companyRegistrationNumber: "50003123456",
  },
]
